### ISSUE TITLE
Add pylonbot tag

### ISSUE THREAD

**Issue by 3kh0** [DevCorner-Github/Pylon-Bot#8]
Add the `pylonbot` tag so more people can find this repo

**Comment by PhantomNimbi** [comment]
Will do. Sorry for the late reply btw. Haven't really done much with the repo in a while and have only just returned to it lol. Didn't think anyone was really using it until now.

**Comment by PhantomNimbi** [comment]
Done. Hope this helps. and again, sorry for the late reply.

**Comment by 3kh0** [comment]
No problem!
